# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Mochi Games' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mochi Games
  pod 'TensorFlowLiteSwift', '0.0.1-nightly'

end
